version: "3.9"

services:

  emailservice:
    image: ttiwari1005/emailservice:latest
    ports:
      - "5000:8080"
    environment:
      - PORT=8080
      - DISABLE_PROFILER=1

  checkoutservice:
    image: ttiwari1005/checkoutservice:latest
    ports:
      - "5050:5050"
    environment:
      - PORT=5050
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - SHIPPING_SERVICE_ADDR=shippingservice:50051
      - PAYMENT_SERVICE_ADDR=paymentservice:50051
      - EMAIL_SERVICE_ADDR=emailservice:5000
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - CART_SERVICE_ADDR=cartservice:7070

  recommendationservice:
    image: ttiwari1005/recommendationservice:latest
    ports:
      - "8081:8080"
    environment:
      - PORT=8080
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - DISABLE_PROFILER=1

  frontend:
    image: ttiwari1005/frontend:latest  # Or use `build: ./frontend` if you have a Dockerfile
    ports:
      - "8085:8080"
    environment:
      - PORT=8080
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - CART_SERVICE_ADDR=cartservice:7070
      - RECOMMENDATION_SERVICE_ADDR=recommendationservice:8080
      - SHIPPING_SERVICE_ADDR=shippingservice:50051
      - CHECKOUT_SERVICE_ADDR=checkoutservice:5050
      - AD_SERVICE_ADDR=adservice:9555
      - ENABLE_PROFILER=0

  paymentservice:
    image: ttiwari1005/paymentservice:latest
    ports:
      - "50051:50051"
    environment:
      - PORT=50051
      - DISABLE_PROFILER=1

  productcatalogservice:
    image: ttiwari1005/productcatalogservice:latest
    ports:
      - "3550:3550"
    environment:
      - PORT=3550
      - DISABLE_PROFILER=1

  cartservice:
    image: ttiwari1005/cartservice:latest  # Or use `build: ./cartservice` if you have a Dockerfile
    ports:
      - "7070:7070"
    environment:
      - REDIS_ADDR=redis-cart:6379
    command: ["./cartservice"]
    depends_on:
      - redis-cart

  currencyservice:
    image: ttiwari1005/currencyservice:latest
    ports:
      - "7000:7000"
    environment:
      - PORT=7000
      - DISABLE_PROFILER=1

  adservice:
    image: ttiwari1005/adservice1:latest  # Or push and use `ttiwari1005/adservice:latest`
    ports:
      - "9555:9555"
    environment:
      - PORT=9555
      - DISABLE_PROFILER=1


  shippingservice:
    image: ttiwari1005/shippingservice:latest
    ports:
      - "50052:50051"  # Changed host port to avoid conflict with paymentservice
    environment:
      - PORT=50051
      - SHIPPING_SERVICE_ADDR=shippingservice:50051  # Fix for missing env var

  redis-cart:
    image: ttiwari1005/redis
    ports:
      - "6379:6379"

  loadgenerator:
    image: ttiwari1005/loadgenerator:latest
    environment:
      - FRONTEND_ADDR=frontend:8080
      - USERS=10
    depends_on:
      - frontend
